In [15]:
def fibonacci(n):
    if n==0:
        print("Input error")
    elif n==1:
        return 0
    elif n==2:
        return 1
    else:
        return fibonacci(n-1) + fibonacci(n-2)

In [47]:
def iterative_factorial(n):
    value = 1
    if n==0:
        return value
    else:
        for i in range(1, n+1):
            value = i*value
        return value

In [50]:
for i in range(10):
    print(iterative_factorial(i))

1
1
2
6
24
120
720
5040
40320
362880


In [29]:
def factorial_(n):
    value =1
    if n ==0:
        return value
    else:
        return n*factorial_(n-1)

In [32]:
factorial_(0)

1

In [57]:
def add_(x):
    return lambda y: x+y

In [58]:
adder = add_(10)

In [59]:
adder(20)

30

In [80]:
import numpy as np
A = np.array([1,2,3,4,5])

In [81]:
B = A[np.newaxis, :]

In [82]:
B = B.T

In [83]:
np.dot(A, B)

array([55])

In [84]:
A@B

array([55])

In [85]:
A*B # Elementwise

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [86]:
A+B

array([[ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10]])

In [88]:
def twice_(x):
    y = x**2
    yield y

In [89]:
twice_(2)

<generator object twice_ at 0x7f7f3a6c3550>