###### These exercises are inspired from Andrew Ng Coursera Deep Learning specialisation and INRIA FUN MOOC on Python 

###### Training section

Broadcasting in python is a mecanism which duplicates a scalar or vector to perform elementwise operations on matrix or vectors

In [52]:
import numpy as np
A = np.random.rand(4,3)
print(A)

[[0.13210844 0.00660831 0.61578517]
 [0.22421646 0.99865737 0.94648596]
 [0.16040349 0.13657746 0.21042498]
 [0.76027989 0.98803149 0.17025292]]


For instance, we can broadcast a scalar b to add b to each element of A

In [2]:
b = 2
A + b

array([[2.5421495 , 2.73973072, 2.49754409],
       [2.59186394, 2.08304993, 2.31127187],
       [2.2168376 , 2.44069079, 2.50183626],
       [2.92520938, 2.17197407, 2.42377685]])

to sum horizontally the elements of A, we can call sum on A with the argument axis = 1

In [3]:
A.sum(axis= 1)

array([1.77942431, 0.98618575, 1.15936466, 1.5209603 ])

to sum vertically, the argument is axis =0

We can do elementwise operations between a matrix with a vector thanks to python broadcasting.
Let's define a vector u as the vertical sum of all columns of A and use it on A

In [4]:
u = A.sum(axis = 0)
print(u)
print(u.shape)

[2.27606042 1.43544552 1.73442908]
(3,)


For security reshape u to force its shape (1,3). Defining a vector with only one dimension, leaving the other empty such as u is defined above, can have terrible cost in debugging.

In [5]:
u = u.reshape(1,3)
print(u.shape)

(1, 3)


divide A by u

In [6]:
div = A/u
print(div)

[[0.23819644 0.5153318  0.28686332]
 [0.26003876 0.05785656 0.17946648]
 [0.09526883 0.30700628 0.28933801]
 [0.40649597 0.11980536 0.24433219]]


We have broadcasted vector u on each element of A

###### Exercise section

Exercise:
compute, for each values of A, its percentage in regard of the total column sum of A and store it in a object w

In [9]:
A.sum(axis=0)[0]

1.9355376745017105

array([[0.31950737, 0.55198704, 0.09241958],
       [0.93503228, 0.94373493, 0.74155077],
       [0.13098196, 0.99003598, 0.54600765],
       [0.55001606, 0.7121703 , 0.64177775]])

In [68]:
B = np.array([[100, 10, 100], [100, 100, 100], [100, 100, 100 ]])
B

array([[100,  10, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [69]:
def compute_percentage(matrix):
        w = []
        for columns in range(0, matrix.shape[1]):
            for i in matrix[:, columns]:
                value = (i/matrix.sum(axis=0)[columns])*100
                w.append(f"{int(value)} %")
        w = np.array(w).reshape(matrix.shape[0], matrix.shape[1])
        print(w)

In [70]:
compute_percentage(B)

[['33 %' '33 %' '33 %']
 ['4 %' '47 %' '47 %']
 ['33 %' '33 %' '33 %']]


In [56]:
A

array([[0.13210844, 0.00660831, 0.61578517],
       [0.22421646, 0.99865737, 0.94648596],
       [0.16040349, 0.13657746, 0.21042498],
       [0.76027989, 0.98803149, 0.17025292]])

In [4]:
np.sum

<function numpy.sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)>

Lets define two matrix with different dimensions, (3, 1) and (1, 5)

In [71]:
col = np.arange(1, 4).reshape((3, 1))
print(col)

[[1]
 [2]
 [3]]


In [72]:
line = 100 * np.arange(1, 6)
print(line)

[100 200 300 400 500]


Add the two matrix col and line thanks to broadcasting

In [76]:
broadcasting = col*line
broadcasting 

array([[ 100,  200,  300,  400,  500],
       [ 200,  400,  600,  800, 1000],
       [ 300,  600,  900, 1200, 1500]])

Broacasting base rules  
We can broadcast A and B when there is a dimension C which 'spreads' both these of A and B  
So we can only broadcast from 1 to n.  
If there is a dimension p> 1 dividing n,  we cannot broadcast from p to n.

Define  

A with dimensions  15 x 3 x 5  
B with dimensions  15 x 1 x 5  
verify A+B has dimensions 15 x 3 x 5  

Try also for 

B is dimensions 3 x 5  
B is dimensions 3 x 1  
B is dimensions 1  

In [80]:
B = np.random.rand(15, 1, 5)
B.shape

(15, 1, 5)

In [90]:
new = A+B
new.shape

(15, 3, 5)

In [89]:
B = np.random.rand(1)

Define A and B with following dimensions and check if you can broadcast

A      2 x 1
B  8 x 4 x 3

In [93]:
A = np.random.rand(2, 1)
B = np.random.rand(8, 4, 3)
A+B

ValueError: operands could not be broadcast together with shapes (2,1) (8,4,3) 

Why this doesn't work?